# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4a7d8887070f516de46aaf4ff34980c8317c880e7549c8418979ad56cb0a95b0e58284fa712db1d46c4bed67f3e629f1e1a53542ef10c6e7fef191758c9e4d39

test:
  secret_key_base: 56e18c30c91b060b6de09f24092a21d9a9beb0a0b62d2c87156e9551096457cba5e9b2b36d4cfda583d094860f95885391b334f068ec007084064d1376177e63

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
